services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: db
    env_file: ".env"
    ports:
      - '5432:5432'
    networks:
      - app-network
  app:
    build: .
    # command: bash -c "poetry run alembic upgrade head"
    env_file: ".env"
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - app-network
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network: