services:
  app:
    build: .
    volumes:
      - ./:/app
    image: bansheebotapp:lastest
    container_name: bansheebot_app
    command: >
      bash -c "poetry install
      && poetry run bot"
    env_file:
      - .env.${BOT_ENV:-dev}
    ports:
      - "3000:3000"
