services:
  db:
    image: postgres:latest
    container_name: bansheebot_db
    env_file: ".dev.env"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app-network
  app:
    build: .
    volumes:
      - ./:/app
    image: bansheebotapp:lastest
    container_name: bansheebot_app
    command: >
      bash -c "poetry install
      && poetry run alembic upgrade head
      && poetry run bot"
    env_file: ".dev.env"
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - app-network
  pgadmin:
    container_name: bansheebot_pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:

volumes:
  pgdata:
  