[tool.poetry]
name = "BansheeBot"
version = "0.1.0"
description = "A discord bot for The Revenants' World of Warcraft guild"
authors = ["Koalth"]
readme = "README.md"
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
httpx = "^0.27.0"
marshmallow = "^3.21.3"
py-cord = "^2.5.0"
ratelimit = "^2.2.1"
python-dotenv = "^1.0.1"
tqdm = "^4.66.4"
datetime = "^5.4"
sqlalchemy = "^2.0.25"
psycopg2-binary = "^2.9.9"

[tool.poetry.scripts]
bansheebot = 'src.__main__:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
