"""init

Revision ID: 3a2fc8480206
Revises: 
Create Date: 2024-08-28 15:15:27.116105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a2fc8480206'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('discord_guild_id', sa.String(), nullable=False),
    sa.Column('default_region', sa.String(), nullable=True),
    sa.Column('default_realm', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_discord_guild_id'), 'settings', ['discord_guild_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_discord_guild_id'), table_name='settings')
    op.drop_table('settings')
    # ### end Alembic commands ###
