"""added character and guild orms

Revision ID: 456da342209b
Revises: 782004c9aeda
Create Date: 2024-09-03 02:42:07.393185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '456da342209b'
down_revision: Union[str, None] = '782004c9aeda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guilds',
    sa.Column('discord_guild_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('realm', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guilds_discord_guild_id'), 'guilds', ['discord_guild_id'], unique=False)
    op.create_index(op.f('ix_guilds_name'), 'guilds', ['name'], unique=False)
    op.create_table('characters',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('realm', sa.String(), nullable=False),
    sa.Column('discord_user_id', sa.String(), nullable=False),
    sa.Column('item_level', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('spec_name', sa.String(), nullable=False),
    sa.Column('profile_url', sa.String(), nullable=False),
    sa.Column('thumbnail_url', sa.String(), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('guild_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_discord_user_id'), 'characters', ['discord_user_id'], unique=False)
    op.create_index(op.f('ix_characters_name'), 'characters', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_characters_name'), table_name='characters')
    op.drop_index(op.f('ix_characters_discord_user_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_guilds_name'), table_name='guilds')
    op.drop_index(op.f('ix_guilds_discord_guild_id'), table_name='guilds')
    op.drop_table('guilds')
    # ### end Alembic commands ###
