"""updated setting

Revision ID: 782004c9aeda
Revises: 3a2fc8480206
Create Date: 2024-09-02 21:36:50.497369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '782004c9aeda'
down_revision: Union[str, None] = '3a2fc8480206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('admin_role_id', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('raider_role_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'raider_role_id')
    op.drop_column('settings', 'admin_role_id')
    # ### end Alembic commands ###
